from selenium import webdriver
from time import sleep
driver = webdriver.Chrome(r'E:\谷歌\chromedriver.exe')
driver.get('http://localhost:8000/#/orders/abandoned_checkouts')
sleep(5)
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[1]/div[2]/form/div/div[1]/div/div[2]/div/span/div/div')
ele.click()
sleep(1)
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[1]/div[2]/form/div/div[2]/div/div[2]/div/span/span/span[1]/div/input')
ele.click()
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[3]/div/div/div/div/div[2]/div[3]')
ele.click()
ele=driver.find_element_by_css_selector('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[1]/div[2]/form/div/div[3]/div/div[2]/div/span/span/span[1]')
ele.click()
sleep(1)
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[1]/div[2]/form/div/div[3]/div/div[2]/div/span/span/span[1]')
ele.click()
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/div/table/tbody/tr[1]/td[2]/button')
ele.click()
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/div/table/tbody/tr[1]/td[2]/button')
ele.click()
ele=driver.find_element_by_xpath('//*[@id="root"]/div/div/section/section/main/div/div/div[1]/div/div/div[2]/div/div/i/svg')
pass 
